"node"

BUILD_TMPL = """\
# GENERATED BY node_archive.bzl
load("@distroless//private/pkg:debian_spdx.bzl", "debian_spdx")
load("@distroless//private/util:merge_providers.bzl", "merge_providers")
load("@distroless//private/util:tar.bzl", "tar")

tar(
    name = "data",
    extension = "tar.gz",
    srcs = glob(
        [
            "output/bin/node",
            "output/LICENSE",
        ],
    ),
    package_dir = "/nodejs",
    strip_prefix = "external/{canonical_name}/output"
)

tar(
    name = "_control",
    extension = "tar.gz",
    srcs = ["control"]
)

debian_spdx(
    name = "spdx",
    control = ":_control",
    data = ":data",
    package_name = "{package_name}",
    spdx_id = "{spdx_id}",
    sha256 = "{sha256}",
    urls = [{urls}]
)

merge_providers(
    name = "{name}",
    srcs = [":data", ":spdx"],
    visibility = ["//visibility:public"],
)
"""

def _impl(rctx):
    rctx.report_progress("Fetching {}".format(rctx.attr.package_name))
    rctx.download_and_extract(
        url = rctx.attr.urls,
        sha256 = rctx.attr.sha256,
        type = rctx.attr.type,
        stripPrefix = rctx.attr.strip_prefix,
        output = "output",
    )
    rctx.template(
        "control",
        rctx.attr.control,
        substitutions = {
            "{{VERSION}}": rctx.attr.version,
            "{{ARCHITECTURE}}": rctx.attr.architecture,
            "{{SHA256}}": rctx.attr.sha256,
        },
    )
    rctx.file(
        "BUILD.bazel",
        content = BUILD_TMPL.format(
            canonical_name = rctx.attr.name,
            name = rctx.attr.name.split("~")[-1],
            package_name = rctx.attr.package_name,
            spdx_id = rctx.attr.name,
            urls = ",".join(['"%s"' % url for url in rctx.attr.urls]),
            sha256 = rctx.attr.sha256,
        ),
    )

node_archive = repository_rule(
    implementation = _impl,
    attrs = {
        "urls": attr.string_list(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "type": attr.string(default = ".tar.gz"),
        "strip_prefix": attr.string(),
        "package_name": attr.string(default = "nodejs"),
        "version": attr.string(mandatory = True),
        "architecture": attr.string(mandatory = True),
        # control is only used to populate the sbom, see https://github.com/GoogleContainerTools/distroless/issues/1373
        # for why writing debian control files to the image is incompatible with scanners.
        "control": attr.label(),
    },
)

_NODE_VERSIONS_TMPL = """\
"node versions"

# AUTO GENERATED. DO NOT EDIT.
NODEJS_VERSIONS = {versions}
"""

def _node_versions_repo_impl(rctx):
    rctx.file("versions.bzl", _NODE_VERSIONS_TMPL.format(versions = str(rctx.attr.versions)))
    rctx.file("BUILD.bazel", 'exports_files(["versions.bzl"])')

node_versions_repo = repository_rule(
    implementation = _node_versions_repo_impl,
    attrs = {
        "versions": attr.string_dict(),
    },
)

def _node_impl(module_ctx):
    mod = module_ctx.modules[0]

    if len(module_ctx.modules) > 1:
        fail("node.archive should be called only once")
    if not mod.is_root:
        fail("node.archive should be called from root module only.")

    # Node (https://nodejs.org/en/about/releases/)
    # Follow Node's maintenance schedule and support all LTS versions that are not end of life

    node_archive(
        name = "nodejs22_amd64",
        sha256 = "b294a556e639d64338823920e5866c21c02741742d2e1529ee1a225c1ec9252a",
        strip_prefix = "node-v22.23.2-linux-x64/",
        urls = ["https://nodejs.org/dist/v22.23.2/node-v22.23.2-linux-x64.tar.gz"],
        version = "22.23.2",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_arm64",
        sha256 = "013b59cfd2819703a6f4a14ab891fc46fc2a4e3f5bcd92de3fb4929b43e35b30",
        strip_prefix = "node-v22.23.2-linux-arm64/",
        urls = ["https://nodejs.org/dist/v22.23.2/node-v22.23.2-linux-arm64.tar.gz"],
        version = "22.23.2",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_arm",
        sha256 = "2a2f59eb8fd9dec27b3bee17c729131d1fd3e6d9943d479f1156ce38af8cd599",
        strip_prefix = "node-v22.23.2-linux-armv7l/",
        urls = ["https://nodejs.org/dist/v22.23.2/node-v22.23.2-linux-armv7l.tar.gz"],
        version = "22.23.2",
        architecture = "arm",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_ppc64le",
        sha256 = "65c8aa9e647196f30d3564bb6b201306b1b520f72f0dd3278da326014a018379",
        strip_prefix = "node-v22.23.2-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v22.23.2/node-v22.23.2-linux-ppc64le.tar.gz"],
        version = "22.23.2",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_s390x",
        sha256 = "986b8441b1d1a01c70ed710bab201741fd0d196d302a7e4338fefd5e1c10e61e",
        strip_prefix = "node-v22.23.2-linux-s390x/",
        urls = ["https://nodejs.org/dist/v22.23.2/node-v22.23.2-linux-s390x.tar.gz"],
        version = "22.23.2",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_loong64",
        sha256 = "90b51d0fc899d5422a80f9abeaa361043b3c8e3c4b9c18e8afc29631dc63f830",
        strip_prefix = "node-v22.23.2-linux-loong64/",
        urls = ["https://github.com/loong64/node/releases/download/v22.23.2/node-v22.23.2-linux-loong64.tar.gz"],
        version = "22.23.2",
        architecture = "loong64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_amd64",
        sha256 = "855d581f8a4eb1a8117e3426de25fe02770592febcfb31369aee1ffbfee9e8ec",
        strip_prefix = "node-v24.20.0-linux-x64/",
        urls = ["https://nodejs.org/dist/v24.20.0/node-v24.20.0-linux-x64.tar.gz"],
        version = "24.20.0",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_arm64",
        sha256 = "3515603e2487879a39bc75716f1a2affd027500c64ba50e845cf72cb33219013",
        strip_prefix = "node-v24.20.0-linux-arm64/",
        urls = ["https://nodejs.org/dist/v24.20.0/node-v24.20.0-linux-arm64.tar.gz"],
        version = "24.20.0",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_ppc64le",
        sha256 = "a734b36c8d1d16ce455c0eb9c329b07dd121c2c8554355064a9861bc96c3adcc",
        strip_prefix = "node-v24.20.0-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v24.20.0/node-v24.20.0-linux-ppc64le.tar.gz"],
        version = "24.20.0",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_s390x",
        sha256 = "d8c224b46ef01f078a523d9b7db79282306fae281e986a15a2dbffe947c5301e",
        strip_prefix = "node-v24.20.0-linux-s390x/",
        urls = ["https://nodejs.org/dist/v24.20.0/node-v24.20.0-linux-s390x.tar.gz"],
        version = "24.20.0",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_loong64",
        sha256 = "63c647e990ec6ee790add384e60c6f835fe9c07c55682ecc5d0fe5570cd46ca4",
        strip_prefix = "node-v24.20.0-linux-loong64/",
        urls = ["https://github.com/loong64/node/releases/download/v24.20.0/node-v24.20.0-linux-loong64.tar.gz"],
        version = "24.20.0",
        architecture = "loong64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_amd64",
        sha256 = "b2b76660fa4ded4e0b2a41ee3c0c651cd52ea8170ead91ebac1e147ac3d55643",
        strip_prefix = "node-v26.8.1-linux-x64/",
        urls = ["https://nodejs.org/dist/v26.8.1/node-v26.8.1-linux-x64.tar.gz"],
        version = "26.8.1",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_arm64",
        sha256 = "d5f973ce975e4bd03e6c2038260f7e9201615aa8e1ee293c72f8dcc2a6d9fddb",
        strip_prefix = "node-v26.8.1-linux-arm64/",
        urls = ["https://nodejs.org/dist/v26.8.1/node-v26.8.1-linux-arm64.tar.gz"],
        version = "26.8.1",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_ppc64le",
        sha256 = "a2d0d12108e2b3cf5691b16054b1b6c5d847d306e6f08d66fdc6363e998c7a39",
        strip_prefix = "node-v26.8.1-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v26.8.1/node-v26.8.1-linux-ppc64le.tar.gz"],
        version = "26.8.1",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_s390x",
        sha256 = "ef6ba7ed4e22a96029d69a5cab91af8e79e5c143c8d633c40983804dcac9822f",
        strip_prefix = "node-v26.8.1-linux-s390x/",
        urls = ["https://nodejs.org/dist/v26.8.1/node-v26.8.1-linux-s390x.tar.gz"],
        version = "26.8.1",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_loong64",
        sha256 = "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5",
        strip_prefix = "node-v26.8.1-linux-loong64/",
        urls = ["https://github.com/loong64/node/releases/download/v26.8.1/node-v26.8.1-linux-loong64.tar.gz"],
        version = "26.8.1",
        architecture = "loong64",
        control = "//nodejs:control",
    )

    node_versions_repo(
        name = "node_versions",
        versions = {
            "22_amd64": "22.23.2",
            "22_arm64": "22.23.2",
            "22_arm": "22.23.2",
            "22_ppc64le": "22.23.2",
            "22_s390x": "22.23.2",
            "22_loong64": "22.23.2",
            "24_amd64": "24.20.0",
            "24_arm64": "24.20.0",
            "24_ppc64le": "24.20.0",
            "24_s390x": "24.20.0",
            "24_loong64": "24.20.0",
            "26_amd64": "26.8.1",
            "26_arm64": "26.8.1",
            "26_ppc64le": "26.8.1",
            "26_s390x": "26.8.1",
            "26_loong64": "26.8.1",
        },
    )

    return module_ctx.extension_metadata(
        root_module_direct_deps = [
            "node_versions",
            "nodejs22_amd64",
            "nodejs22_arm64",
            "nodejs22_arm",
            "nodejs22_ppc64le",
            "nodejs22_s390x",
            "nodejs22_loong64",
            "nodejs24_amd64",
            "nodejs24_arm64",
            "nodejs24_ppc64le",
            "nodejs24_s390x",
            "nodejs24_loong64",
            "nodejs26_amd64",
            "nodejs26_arm64",
            "nodejs26_ppc64le",
            "nodejs26_s390x",
            "nodejs26_loong64",
        ],
        root_module_direct_dev_deps = [],
    )

_archive = tag_class(attrs = {})

node = module_extension(
    implementation = _node_impl,
    tag_classes = {
        "archive": _archive,
    },
)
