"node"

BUILD_TMPL = """\
# GENERATED BY node_archive.bzl
load("@distroless//private/pkg:debian_spdx.bzl", "debian_spdx")
load("@distroless//private/util:merge_providers.bzl", "merge_providers")
load("@distroless//private/util:tar.bzl", "tar")

tar(
    name = "data",
    extension = "tar.gz",
    srcs = glob(
        [
            "output/bin/node",
            "output/LICENSE",
        ],
    ),
    package_dir = "/nodejs",
    strip_prefix = "external/{canonical_name}/output"
)

tar(
    name = "_control",
    extension = "tar.gz",
    srcs = ["control"]
)

debian_spdx(
    name = "spdx",
    control = ":_control",
    data = ":data",
    package_name = "{package_name}",
    spdx_id = "{spdx_id}",
    sha256 = "{sha256}",
    urls = [{urls}]
)

merge_providers(
    name = "{name}",
    srcs = [":data", ":spdx"],
    visibility = ["//visibility:public"],
)
"""

def _impl(rctx):
    rctx.report_progress("Fetching {}".format(rctx.attr.package_name))
    rctx.download_and_extract(
        url = rctx.attr.urls,
        sha256 = rctx.attr.sha256,
        type = rctx.attr.type,
        stripPrefix = rctx.attr.strip_prefix,
        output = "output",
    )
    rctx.template(
        "control",
        rctx.attr.control,
        substitutions = {
            "{{VERSION}}": rctx.attr.version,
            "{{ARCHITECTURE}}": rctx.attr.architecture,
            "{{SHA256}}": rctx.attr.sha256,
        },
    )
    rctx.file(
        "BUILD.bazel",
        content = BUILD_TMPL.format(
            canonical_name = rctx.attr.name,
            name = rctx.attr.name.split("~")[-1],
            package_name = rctx.attr.package_name,
            spdx_id = rctx.attr.name,
            urls = ",".join(['"%s"' % url for url in rctx.attr.urls]),
            sha256 = rctx.attr.sha256,
        ),
    )

node_archive = repository_rule(
    implementation = _impl,
    attrs = {
        "urls": attr.string_list(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "type": attr.string(default = ".tar.gz"),
        "strip_prefix": attr.string(),
        "package_name": attr.string(default = "nodejs"),
        "version": attr.string(mandatory = True),
        "architecture": attr.string(mandatory = True),
        # control is only used to populate the sbom, see https://github.com/GoogleContainerTools/distroless/issues/1373
        # for why writing debian control files to the image is incompatible with scanners.
        "control": attr.label(),
    },
)

_NODE_VERSIONS_TMPL = """\
"node versions"

# AUTO GENERATED. DO NOT EDIT.
NODEJS_VERSIONS = {versions}
"""

def _node_versions_repo_impl(rctx):
    rctx.file("versions.bzl", _NODE_VERSIONS_TMPL.format(versions = str(rctx.attr.versions)))
    rctx.file("BUILD.bazel", 'exports_files(["versions.bzl"])')

node_versions_repo = repository_rule(
    implementation = _node_versions_repo_impl,
    attrs = {
        "versions": attr.string_dict(),
    },
)

def _node_impl(module_ctx):
    mod = module_ctx.modules[0]

    if len(module_ctx.modules) > 1:
        fail("node.archive should be called only once")
    if not mod.is_root:
        fail("node.archive should be called from root module only.")

    # Node (https://nodejs.org/en/about/releases/)
    # Follow Node's maintenance schedule and support all LTS versions that are not end of life

    node_archive(
        name = "nodejs22_amd64",
        sha256 = "b294a556e639d64338823920e5866c21c02741742d2e1529ee1a225c1ec9252a",
        strip_prefix = "node-v22.23.2-linux-x64/",
        urls = ["https://nodejs.org/dist/v22.23.2/node-v22.23.2-linux-x64.tar.gz"],
        version = "22.23.2",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_arm64",
        sha256 = "013b59cfd2819703a6f4a14ab891fc46fc2a4e3f5bcd92de3fb4929b43e35b30",
        strip_prefix = "node-v22.23.2-linux-arm64/",
        urls = ["https://nodejs.org/dist/v22.23.2/node-v22.23.2-linux-arm64.tar.gz"],
        version = "22.23.2",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_arm",
        sha256 = "2a2f59eb8fd9dec27b3bee17c729131d1fd3e6d9943d479f1156ce38af8cd599",
        strip_prefix = "node-v22.23.2-linux-armv7l/",
        urls = ["https://nodejs.org/dist/v22.23.2/node-v22.23.2-linux-armv7l.tar.gz"],
        version = "22.23.2",
        architecture = "arm",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_ppc64le",
        sha256 = "65c8aa9e647196f30d3564bb6b201306b1b520f72f0dd3278da326014a018379",
        strip_prefix = "node-v22.23.2-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v22.23.2/node-v22.23.2-linux-ppc64le.tar.gz"],
        version = "22.23.2",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_s390x",
        sha256 = "986b8441b1d1a01c70ed710bab201741fd0d196d302a7e4338fefd5e1c10e61e",
        strip_prefix = "node-v22.23.2-linux-s390x/",
        urls = ["https://nodejs.org/dist/v22.23.2/node-v22.23.2-linux-s390x.tar.gz"],
        version = "22.23.2",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_loong64",
        sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        strip_prefix = "node-v22.23.2-linux-loong64/",
        urls = ["https://github.com/loong64/node/releases/download/v22.23.2/node-v22.23.2-linux-loong64.tar.gz"],
        version = "22.23.2",
        architecture = "loong64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_amd64",
        sha256 = "9f5eb6ac21845a66c493c91a253b1da32fd684e89e9b7202d4936982336be4ca",
        strip_prefix = "node-v24.18.1-linux-x64/",
        urls = ["https://nodejs.org/dist/v24.18.1/node-v24.18.1-linux-x64.tar.gz"],
        version = "24.18.1",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_arm64",
        sha256 = "df224555a083b918e46260cc969838501b9f9a87140c1195e5b9597b56d5dae2",
        strip_prefix = "node-v24.18.1-linux-arm64/",
        urls = ["https://nodejs.org/dist/v24.18.1/node-v24.18.1-linux-arm64.tar.gz"],
        version = "24.18.1",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_ppc64le",
        sha256 = "4a8c6209ba3a5aea84c40201d896624ed706b9799a6dc54cbd965433a369a3d0",
        strip_prefix = "node-v24.18.1-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v24.18.1/node-v24.18.1-linux-ppc64le.tar.gz"],
        version = "24.18.1",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_s390x",
        sha256 = "62ad850efefa9ab42a3e901d8e0de86d71bf9c8a0c389dabed248f1ec9590c5a",
        strip_prefix = "node-v24.18.1-linux-s390x/",
        urls = ["https://nodejs.org/dist/v24.18.1/node-v24.18.1-linux-s390x.tar.gz"],
        version = "24.18.1",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_loong64",
        sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        strip_prefix = "node-v24.18.1-linux-loong64/",
        urls = ["https://github.com/loong64/node/releases/download/v24.18.1/node-v24.18.1-linux-loong64.tar.gz"],
        version = "24.18.1",
        architecture = "loong64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_amd64",
        sha256 = "2b07f09c218d473a26442bff5a90151f53f7b7c0a23bad244eda2c26303a2ba7",
        strip_prefix = "node-v26.5.1-linux-x64/",
        urls = ["https://nodejs.org/dist/v26.5.1/node-v26.5.1-linux-x64.tar.gz"],
        version = "26.5.1",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_arm64",
        sha256 = "21194bbf41c18d9ec277545c4d14cce8597d57a9d9f494c323d8121a25de33e8",
        strip_prefix = "node-v26.5.1-linux-arm64/",
        urls = ["https://nodejs.org/dist/v26.5.1/node-v26.5.1-linux-arm64.tar.gz"],
        version = "26.5.1",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_ppc64le",
        sha256 = "cf518dd2772ea7e5046daf4a4ba9e348fce01e2b9741f32ba21b4bbd87b8dfaf",
        strip_prefix = "node-v26.5.1-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v26.5.1/node-v26.5.1-linux-ppc64le.tar.gz"],
        version = "26.5.1",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_s390x",
        sha256 = "af5a58fca0c3fc130c6a649bd6c29f4b000145055eb7a364bde189abdf1516f5",
        strip_prefix = "node-v26.5.1-linux-s390x/",
        urls = ["https://nodejs.org/dist/v26.5.1/node-v26.5.1-linux-s390x.tar.gz"],
        version = "26.5.1",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_loong64",
        sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        strip_prefix = "node-v26.5.1-linux-loong64/",
        urls = ["https://github.com/loong64/node/releases/download/v26.5.1/node-v26.5.1-linux-loong64.tar.gz"],
        version = "26.5.1",
        architecture = "loong64",
        control = "//nodejs:control",
    )

    node_versions_repo(
        name = "node_versions",
        versions = {
            "22_amd64": "22.23.2",
            "22_arm64": "22.23.2",
            "22_arm": "22.23.2",
            "22_ppc64le": "22.23.2",
            "22_s390x": "22.23.2",
            "22_loong64": "22.23.2",
            "24_amd64": "24.18.1",
            "24_arm64": "24.18.1",
            "24_ppc64le": "24.18.1",
            "24_s390x": "24.18.1",
            "24_loong64": "24.18.1",
            "26_amd64": "26.5.1",
            "26_arm64": "26.5.1",
            "26_ppc64le": "26.5.1",
            "26_s390x": "26.5.1",
            "26_loong64": "26.5.1",
        },
    )

    return module_ctx.extension_metadata(
        root_module_direct_deps = [
            "node_versions",
            "nodejs22_amd64",
            "nodejs22_arm64",
            "nodejs22_arm",
            "nodejs22_ppc64le",
            "nodejs22_s390x",
            "nodejs22_loong64",
            "nodejs24_amd64",
            "nodejs24_arm64",
            "nodejs24_ppc64le",
            "nodejs24_s390x",
            "nodejs24_loong64",
            "nodejs26_amd64",
            "nodejs26_arm64",
            "nodejs26_ppc64le",
            "nodejs26_s390x",
            "nodejs26_loong64",
        ],
        root_module_direct_dev_deps = [],
    )

_archive = tag_class(attrs = {})

node = module_extension(
    implementation = _node_impl,
    tag_classes = {
        "archive": _archive,
    },
)
