name: snapshots
on:
  workflow_dispatch: # Allow manual runs.
  # will send emails to last editor of this cron syntax (distroless-bot)
  schedule:
    - cron:  '0 0 1 * *'
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      id: go
      with:
        go-version: 'stable'
        cache-dependency-path: debian_package_manager/go.sum

    - name: Run update script
      run: ./updateWorkspaceSnapshots.sh
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        author: GitHub <actions@github.com>
        committer: GitHub <actions@github.com>
        commit-message: 'feat: update packages'
        branch: feat/update-packages
        delete-branch: true
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Update package snapshots
        body: |
          Update package snapshots
        labels: |
          dependencies
